### ISSUE TITLE
ebooklib cannot generate navigation for articles with emojis

### ISSUE THREAD

**Issue by jacobbudin** [jacobbudin/portable-wisdom#17]
[`ebooklib._get_nav`](https://pypi.org/project/EbookLib/) fails when any article contains an emoji:

> lxml.etree.ParserError: Document is empty

```
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/portable_wisdom/wisdom.py", line 86, in <module>
    main()
  File "/portable_wisdom/wisdom.py", line 80, in main
    epub.write_epub(filename, book, {})
  File "/venv/lib/python3.10/site-packages/ebooklib/epub.py", line 1746, in write_epub
    epub.write()
  File "/venv/lib/python3.10/site-packages/ebooklib/epub.py", line 1369, in write
    self._write_items()
  File "/venv/lib/python3.10/site-packages/ebooklib/epub.py", line 1356, in _write_items
    self.out.writestr('%s/%s' % (self.book.FOLDER_NAME, item.file_name), self._get_nav(item))
  File "/venv/lib/python3.10/site-packages/ebooklib/epub.py", line 1212, in _get_nav
    inserted_pages = get_pages_for_items([item for item in self.book.get_items_of_type(ebooklib.ITEM_DOCUMENT)   File "/venv/lib/python3.10/site-packages/ebooklib/utils.py", line 119, in get_pages_for_items
    pages_from_docs = [get_pages(item) for item in items]
  File "/venv/lib/python3.10/site-packages/ebooklib/utils.py", line 119, in <listcomp>
    pages_from_docs = [get_pages(item) for item in items]
  File "/venv/lib/python3.10/site-packages/ebooklib/utils.py", line 96, in get_pages
    body = parse_html_string(item.get_body_content())
  File "/venv/lib/python3.10/site-packages/ebooklib/utils.py", line 48, in parse_html_string
    html_tree = html.document_fromstring(s, parser=utf8_parser)
  File "/venv/lib/python3.10/site-packages/lxml/html/__init__.py", line 761, in document_fromstring
    raise etree.ParserError(
lxml.etree.ParserError: Document is empty
```

**Comment by jacobbudin** [comment]
Possible solutions:
1. Encode emojis as HTML entities.
2. Remove emojis (e.g., [`emoji.demojize`](https://github.com/carpedm20/emoji/blob/1367bf8d5751d182e4f278cab7ce248716fe71f9/emoji/core.py#L55)).

Do most e-readers' support displaying emojis?
